### PR TITLE
Add HEAD method

### PR DESCRIPTION
**Pull request by tbussmann**
this adds a http_method HEAD which does skip the content and does not follow redirections. Also it prepares for a version 1.3 incl. migration from 1.1. I'm not sure this the proper way but master was on 1.1 while 1.2 already released w/o changes in the SQL interface.

### CODE REVIEW

**Comment by pramsey** [comment]
I admit to being a little distracted, but where is 1.2 released?

**Comment by tbussmann** [comment]
sorry, I confused 1.1.2 with 1.2

**Comment by pramsey** [comment]
If you want to tell me to buzz off, feel free, but would you mind doing a little experiment? I hate burning new version numbers, and I wonder if we can do it w/o creating whole new .sql version files. Does it work if we have just a 1.0.sql file, and then only the 1.0--1.1 and 1.1--1.2 files? So each version only includes the alterations necessary to update. The experiment is basically whether the extension system knows that to install 1.3 it has to install 1.0 and then overlay the update files on top. Or maybe we should have a 1.3 file only and just the upgrade files... I just hate having the growing collection of version files, it offends my aesthetics.

**Comment by tbussmann** [comment]
The idea sounds appealing, but unfortunately won't work out. In The [Docs](https://www.postgresql.org/docs/9.6/static/extend-extensions.html#AEN61880) there is mentioned: 

> There must also be at least one SQL script file, which follows the naming pattern extension--version.sql

The clever shortest path search used for updates is not usable for initial CREATE EXTENSION. Anyway, I've tried the experiment and got some more insight. I've placed my [psql log in a gist](https://gist.github.com/tbussmann/b507bd116e85873b8edc091072f0e35a). Direct install of 1.2 is not possible due to lacking direct script. Install of 1.0 is not possible due to incompatible library.

So with each released version there probably should be the newest .sql and direct upgrade scripts to that version from all previous versions that have an incompatible API in the .so. For the remaining incremental scripts can be used. oh my.

If you keep the master branch at the next (or a special fake) version between releases it would ease pull requests adding to that and brings you as the maintainer in control to decide when a next version number shall be used, tagged and released.

**Comment by tbussmann** [comment]
> The clever shortest path search used for updates is not usable for initial CREATE EXTENSION. 

FYI: this is going to change for PostgreSQL 10, see [this commit](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=40b449ae8;hp=28e5e5648cc3666537c393b2636c4aa34fdb22c1). The problem with (in)compatible libraries remains, thus.

**Pull request merged**
