### PR TITLE
Support pgsql interrupt of HTTP request

### PR DESCRIPTION
**Pull request by pramsey**

### CODE REVIEW

**Comment by pramsey** [comment]
@robe2 does this branch work for you? (aka, windows)

**Comment by robe2** [comment]
@pramsey  It compiles.  How do I test it?

**Comment by pramsey** [comment]
Set the timeout to a long time, and then run a query against http://httpbin.org/delay/10 and hit ctrl-c on the query before it has a chance to return. It should return "HTTP request cancelled" if all the callbacks/hooks work

**Comment by robe2** [comment]
I think it's working, but had to increase delay to 20 since it took 10 secs before interrupt canceled.

`
  set http.timeout_msec = 40000;
  SELECT * FROM http_get('http://httpbin.org/delay/20');

`

then hitting ctrl-x-c

> Cancel request sent
Time: 10150.654 ms (00:10.151)

**Comment by robe2** [comment]
Oh wait I thought the 20 would make it take 20 seconds to return, but I guess max is 10.  Hmm so it's a bit inconclusive.  I think it works cause it does do a cancel, doesn't return a result, but timing is too close to call.

**Comment by pramsey** [comment]
Yeah, that's not what I wanted, it should return "HTTP request cancelled". What you got indicates, I think, that it just ran to conclusion then your signal finally happened. You should be able to get a cancel immediately (somewhat) after you hit ctrl-c. Grm.

**Comment by robe2** [comment]
bummer, so how long does it take to cancel for you?  I recall we had same issue in PostGIS when @strk introduced interrupts, but he was able to change something to make it work under windows as well

**Comment by pramsey** [comment]
It takes maybe 0.5 seconds to cancel for me. There's some magic code in the postgis interrupt handler that is clearly for windows, so I'll have to figure out where to insert that in my own interrupt code.

**Comment by robe2** [comment]
It works it works 👍 

```sql
set http.timeout_msec = 40000;
SELECT * FROM http_get('http://httpbin.org/delay/10');
```

Now hitting cancel

> Cancel request sent
ERROR:  HTTP request cancelled
Time: 1000.451 ms (00:01.000)


Did you put in a regress test?  I don't recall seeing this before:

> ============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test http                     ... ok

=====================
 All 1 tests passed.
=====================

**Pull request merged**
