### PR TITLE
Add http_set_curlopt facility for setting strange curl options.

### PR DESCRIPTION
**Pull request by pramsey**

### CODE REVIEW

**Comment by robe2** [comment]
This doesn't compile for me.  I get this error.  I confirmed current head compiles and installs fine for me, but not after I apply this patch.  I have CURL 7.44.0 in case that matters.

`
http.c:117:28: error: 'CURLOPT_PRE_PROXY' undeclared here (not in a function)
     { "CURLOPT_PRE_PROXY", CURLOPT_PRE_PROXY, CURLOPT_STRING, false },
                            ^
http.c:124:41: error: 'CURLOPT_PROXY_TLSAUTH_USERNAME' undeclared here (not in a function)
     { "CURLOPT_PROXY_TLSAUTH_USERNAME", CURLOPT_PROXY_TLSAUTH_USERNAME, CURLOPT_STRING, false },
                                         ^
http.c:125:41: error: 'CURLOPT_PROXY_TLSAUTH_PASSWORD' undeclared here (not in a function)
     { "CURLOPT_PROXY_TLSAUTH_PASSWORD", CURLOPT_PROXY_TLSAUTH_PASSWORD, CURLOPT_STRING, false },
                                         ^
http.c:127:37: error: 'CURLOPT_PROXY_TLSAUTH_TYPE' undeclared here (not in a function)
     { "CURLOPT_PROXY_TLSAUTH_TYPE", CURLOPT_PROXY_TLSAUTH_TYPE, CURLOPT_STRING, false },
                                     ^
<builtin>: recipe for target 'http.o' failed
make: *** [http.o] Error 1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2  -I/projects/curl/rel-curl-7.44.0w64gcc48/include -I/projects/pcre/rel-8.33w64gcc48/include -I/projects/libxml/rel-libxml2-2.7.8w64gcc48/include/libxml2 -I. -I./ -IC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/include/server -IC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/include/internal -I./src/include/port/win32 -DEXEC_BACKEND -I/projects/libxml/rel-libxml2-2.7.8w64gcc48/include/libxml2   -IC:/MING64~1/projects/POSTGR~1/rel/PG10W6~2/include/server/port/win32  -c -o http.o http.c
http.c:117:28: error: 'CURLOPT_PRE_PROXY' undeclared here (not in a function)
     { "CURLOPT_PRE_PROXY", CURLOPT_PRE_PROXY, CURLOPT_STRING, false },
                            ^
http.c:124:41: error: 'CURLOPT_PROXY_TLSAUTH_USERNAME' undeclared here (not in a function)
     { "CURLOPT_PROXY_TLSAUTH_USERNAME", CURLOPT_PROXY_TLSAUTH_USERNAME, CURLOPT_STRING, false },
                                         ^
http.c:125:41: error: 'CURLOPT_PROXY_TLSAUTH_PASSWORD' undeclared here (not in a function)
     { "CURLOPT_PROXY_TLSAUTH_PASSWORD", CURLOPT_PROXY_TLSAUTH_PASSWORD, CURLOPT_STRING, false },
                                         ^
http.c:127:37: error: 'CURLOPT_PROXY_TLSAUTH_TYPE' undeclared here (not in a function)
     { "CURLOPT_PROXY_TLSAUTH_TYPE", CURLOPT_PROXY_TLSAUTH_TYPE, CURLOPT_STRING, false },
                                     ^
<builtin>: recipe for target 'http.o' failed
make: *** [http.o] Error 1

`

**Comment by robe2** [comment]
Okay I was able to get this to work by remarking out all the TLS variables.  I guess I don't have my curl compiled with TLS support. Not sure how easy it is to check that.  I suspect people who didn't compile with SSL support will have similar issues with anything SSL.

The thing I don't like about this is I have to run the function for each session I want to use the setting, as opposed to just setting it once in System or in database GUC.

Stupid thought, you think you can create a table to store these settings and read them so they are maintained at least for the database. Otherwise got to change my code everywhere I use this to include this extra function call.  Which at the moment is a PITA.

**Comment by pramsey** [comment]
Yeah, but the whole point of this is to avoid GUCs. The only alternatives in my mind are (a) including options in every http_*() call and (b) this session-based thing, which happens to work because we keep the CURL* lying around in a global. No, there will not be a magic table. These fixes are for the 2% of the population who need options beyond the defaults, so nothing will get uglier in the default use case. That's actually why I didn't do the option-every-time approach, since it involves mucking with all the function signatures. Though I could be persuaded to do it, still, since it's programatically the cleanest and most consistent with HTTP as a stateless protocol, and it's also consistent with the CURL API.

**Comment by pramsey** [comment]
I built/tested against curl 7.54.0. It may well be that there are options unavailable there. I guess I'll have to hide these in levels of curl version testing. I wonder if there's a dictionary of what version each curlopt was added in.

**Comment by robe2** [comment]
I said it was a stupid idea :).  Anyway your function approach I prefer over the adding args to every call.
I suppose I could get around the issue by putting a wrapper around all the functions I use that does the set before calling the function.  I'll have to give that a try.

**Comment by pramsey** [comment]
But, but, if you do a wrapper you're basically doing the "extra args"
solution....???

**Comment by robe2** [comment]
Not exactly.  my function is taking no additional args (same signature as your existing), but has the settings I need hard-coded in the function so I can pretend I'm in the 98% of the population that doesn't need anything set.

**Comment by robe2** [comment]
As an extra datapoint I compiled against my curl 7.48.0 and had the same issue.  I tested against 7.54.1 and it was fine.

I wonder if the change happened around 7.52, based on this note here:

https://curl.haxx.se/docs/sslcerts.html

> HTTPS proxy

Since version 7.52.0, curl can do HTTPS to the proxy separately from the connection to the server. This TLS connection is handled separately from the server connection so instead of --insecure and --cacert to control the certificate verification, you use --proxy-insecure and --proxy-cacert. With these options, you make sure that the TLS connection and the trust of the proxy can be kept totally separate from the TLS connection to the server.

**Comment by pramsey** [comment]
Check if the new version guards help.

**Comment by robe2** [comment]
Seems to work.  It compiled at any rate didn't test it.

I do see some warnings, but those might have been there before and I just wasn't paying attention.
This shows both compiling against 7.44.0 and 7.54.1

> C:/ming64gcc48/projects/curl/rel-curl-7.44.0w64gcc48/include/curl/typecheck-gcc.h:47:9: warning: call to '_curl_easy_setopt_err_long' declared with attribute warning: curl_easy_setopt expects a long argument for this option
         _curl_easy_setopt_err_long();                                         \
         ^
http.c:232:8: note: in expansion of macro 'curl_easy_setopt'
  err = curl_easy_setopt((handle), (opt), (value)); \
        ^
http.c:814:4: note: in expansion of macro 'CURL_SETOPT'
    CURL_SETOPT(g_http_handle, CURLOPT_INFILESIZE, content_size);
    ^

**Comment by robe2** [comment]
oops hold on spoke too soon.  You put 

    { "CURLOPT_CAINFO", CURLOPT_CAINFO, CURLOPT_STRING, false },

under 7.52.  That isn't right.  That has existed for quite some time and what I was using to override ssl bundle.

**Comment by robe2** [comment]
@pramsey 
Okay that last commit works with no errors and I can set the CURLOPT_CAINFO with my 7.44.0 again and access https sites.

Thanks

**Pull request merged**
